// <auto-generated />
namespace DentalWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dental : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dental));
        
        string IMigrationMetadata.Id
        {
            get { return "201812211517176_dental"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
